name       : python-mediafile
version    : 0.2.0
release    : 4
source     :
    - https://github.com/beetbox/mediafile/archive/refs/tags/v0.2.0.tar.gz : a91cf41a24d24893f72593482a7c5ceb4da5313486e016f5b3a045f29833d2a4
license    : MIT
component  : programming.python
summary    : MediaFile is a simple interface to the metadata tags for many audio file formats. It wraps Mutagen, a high-quality library for low-level tag manipulation, with a high-level, format-independent
    interface for a common set of tags.
description: |
    MediaFile is a simple interface to the metadata tags for many audio file formats. It wraps Mutagen, a high-quality library for low-level tag manipulation, with a high-level, format-independent interface for a common set of tags.
builddeps  :
    - mutagen
    - python-six
rundeps    :
    - mutagen
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
