name       : python-mediafile
version    : 0.9.0
release    : 6
source     :
    - https://github.com/beetbox/mediafile/archive/refs/tags/v0.9.0.tar.gz : 035e8731c82d1135c7c8b4260d818901d99fa876727a602da81646e37023d2dd
homepage   : https://github.com/beetbox/mediafile
license    : MIT
component  : programming.python
summary    : Read and write audio files' tags in Python
description: |
    MediaFile is a simple interface to the metadata tags for many audio file formats. It wraps Mutagen, a high-quality library for low-level tag manipulation, with a high-level, format-independent interface for a common set of tags.
builddeps  :
    - mutagen          # check
    - python-build
    - python-flit-core
    - python-installer
    - python-nose      # check
    - python-packaging
rundeps    :
    - mutagen
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests
