name       : python-mediafile
version    : 0.9.0
release    : 5
source     :
    - https://github.com/beetbox/mediafile/archive/refs/tags/v0.9.0.tar.gz : 035e8731c82d1135c7c8b4260d818901d99fa876727a602da81646e37023d2dd
homepage   : https://github.com/beetbox/mediafile
license    : MIT
component  : programming.python
networking : yes
summary    : Read and write audio files' tags in Python
description: |
    MediaFile is a simple interface to the metadata tags for many audio file formats. It wraps Mutagen, a high-quality library for low-level tag manipulation, with a high-level, format-independent interface for a common set of tags.
builddeps  :
    - mutagen
    - python-nose
    - python-six
rundeps    :
    - mutagen
    - python-six
build      : |
    # Installing flip as user for now to skip packaging 5 new python packages.
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    pip3 install --user flip
    python3 -m pip wheel --no-deps .
install    : |
    unset PYTHONUSERBASE
    python3 -m pip install --root=%installroot% --no-deps *.whl
check      : |
    %python3_test nosetests
